### ISSUE TITLE
Genivi audio manager plugin issue

### ISSUE THREAD

**Issue by dchristogam** [COVESA/capicxx-dbus-tools#10]
I downloaded Common api 3.2.0 version from Git and i compiled AudioManger v8.0 sucessfully. But i cant able to compile AudioManager Plugins. Im getting below error,
 33%] Built target CommandInterfaceProviderSomeIpStub
[ 50%] Building CXX object PluginCommandInterfaceCAPI/CMakeFiles/PluginCommandInterfaceCAPI.dir/src/CAmCommandSenderCAPI.cpp.o
In file included from /usr/include/x86_64-linux-gnu/c++/5/bits/c++allocator.h:33:0,
                 from /usr/include/c++/5/bits/allocator.h:46,
                 from /usr/include/c++/5/bits/stl_tree.h:64,
                 from /usr/include/c++/5/map:60,
                 from /home/guruprasath/Documents/GAM/AudioManagerPlugins/PluginCommandInterfaceCAPI/include/CAmCommandSenderCAPI.h:21,
                 from /home/guruprasath/Documents/GAM/AudioManagerPlugins/PluginCommandInterfaceCAPI/src/CAmCommandSenderCAPI.cpp:18:
/usr/include/c++/5/ext/new_allocator.h: In instantiation of â€˜void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = am::CAmCommandSenderService; _Args = {am::IAmCommandReceive*&}; _Tp = am::CAmCommandSenderService]â€™:
/usr/include/c++/5/bits/alloc_traits.h:530:4:   required from â€˜static void std::allocator_traits<std::allocator<_Tp1> >::construct(std::allocator_traits<std::allocator<_Tp1> >::allocator_type&, _Up*, _Args&& ...) [with _Up = am::CAmCommandSenderService; _Args = {am::IAmCommandReceive*&}; _Tp = am::CAmCommandSenderService; std::allocator_traits<std::allocator<_Tp1> >::allocator_type = std::allocator<am::CAmCommandSenderService>]â€™
/usr/include/c++/5/bits/shared_ptr_base.h:522:39:   required from â€˜std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {am::IAmCommandReceive*&}; _Tp = am::CAmCommandSenderService; _Alloc = std::allocator<am::CAmCommandSenderService>; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]â€™
/usr/include/c++/5/bits/shared_ptr_base.h:617:4:   required from â€˜std::__shared_count<_Lp>::__shared_count(std::_Sp_make_shared_tag, _Tp*, const _Alloc&, _Args&& ...) [with _Tp = am::CAmCommandSenderService; _Alloc = std::allocator<am::CAmCommandSenderService>; _Args = {am::IAmCommandReceive*&}; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]â€™
/usr/include/c++/5/bits/shared_ptr_base.h:1097:35:   required from â€˜std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<am::CAmCommandSenderService>; _Args = {am::IAmCommandReceive*&}; _Tp = am::CAmCommandSenderService; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]â€™
/usr/include/c++/5/bits/shared_ptr.h:319:64:   required from â€˜std::shared_ptr<_Tp>::shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<am::CAmCommandSenderService>; _Args = {am::IAmCommandReceive*&}; _Tp = am::CAmCommandSenderService]â€™
/usr/include/c++/5/bits/shared_ptr.h:620:39:   required from â€˜std::shared_ptr<_Tp1> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = am::CAmCommandSenderService; _Alloc = std::allocator<am::CAmCommandSenderService>; _Args = {am::IAmCommandReceive*&}]â€™
/usr/include/c++/5/bits/shared_ptr.h:635:39:   required from â€˜std::shared_ptr<_Tp1> std::make_shared(_Args&& ...) [with _Tp = am::CAmCommandSenderService; _Args = {am::IAmCommandReceive*&}]â€™
/home/guruprasath/Documents/GAM/AudioManagerPlugins/PluginCommandInterfaceCAPI/src/CAmCommandSenderCAPI.cpp:82:79:   required from here
/usr/include/c++/5/ext/new_allocator.h:120:4: error: invalid new-expression of abstract class type â€˜am::CAmCommandSenderServiceâ€™
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
In file included from /home/guruprasath/Documents/GAM/AudioManagerPlugins/PluginCommandInterfaceCAPI/include/CAmCommandSenderCAPI.h:24:0,
                 from /home/guruprasath/Documents/GAM/AudioManagerPlugins/PluginCommandInterfaceCAPI/src/CAmCommandSenderCAPI.cpp:18:
/home/guruprasath/Documents/GAM/AudioManagerPlugins/PluginCommandInterfaceCAPI/include/CAmCommandSenderService.h:34:7: note:   because the following virtual functions are pure within â€˜am::CAmCommandSenderServiceâ€™:
 class CAmCommandSenderService: public v1::org::genivi::am::commandinterface::CommandControlStubDefault {
       ^
In file included from /home/guruprasath/Documents/GAM/AudioManagerPlugins/build/PluginCommandInterfaceCAPI/src-gen/v320/Generic/v1/org/genivi/am/commandinterface/CommandControlStub.hpp:43:0,
                 from /home/guruprasath/Documents/GAM/AudioManagerPlugins/build/PluginCommandInterfaceCAPI/src-gen/v320/Generic/v1/org/genivi/am/commandinterface/CommandControlStubDefault.hpp:22,
                 from /home/guruprasath/Documents/GAM/AudioManagerPlugins/PluginCommandInterfaceCAPI/include/CAmCommandSenderService.h:22,
                 from /home/guruprasath/Documents/GAM/AudioManagerPlugins/PluginCommandInterfaceCAPI/include/CAmCommandSenderCAPI.h:24,
                 from /home/guruprasath/Documents/GAM/AudioManagerPlugins/PluginCommandInterfaceCAPI/src/CAmCommandSenderCAPI.cpp:18:
/usr/local/include/CommonAPI-3.2/CommonAPI/Stub.hpp:34:18: note: 	virtual bool CommonAPI::StubBase::hasElement(uint32_t) const
     virtual bool hasElement(const uint32_t _id) const = 0;
                  ^
/usr/local/include/CommonAPI-3.2/CommonAPI/Stub.hpp:34:18: note: 	virtual bool CommonAPI::StubBase::hasElement(uint32_t) const
cc1plus: warning: unrecognized command line option â€˜-Wno-variadic-macroâ€™
PluginCommandInterfaceCAPI/CMakeFiles/PluginCommandInterfaceCAPI.dir/build.make:110: recipe for target 'PluginCommandInterfaceCAPI/CMakeFiles/PluginCommandInterfaceCAPI.dir/src/CAmCommandSenderCAPI.cpp.o' failed
make[2]: *** [PluginCommandInterfaceCAPI/CMakeFiles/PluginCommandInterfaceCAPI.dir/src/CAmCommandSenderCAPI.cpp.o] Error 1
CMakeFiles/Makefile2:188: recipe for target 'PluginCommandInterfaceCAPI/CMakeFiles/PluginCommandInterfaceCAPI.dir/all' failed
make[1]: *** [PluginCommandInterfaceCAPI/CMakeFiles/PluginCommandInterfaceCAPI.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by varunsunagar** [comment]
I am finding same issue, could anyone help out to solve?

**Comment by goncaloalmeida** [comment]
@dchristogam you are still with this problem?
