### ISSUE TITLE
Where is the built code generator?

### ISSUE THREAD

**Issue by qiali65** [COVESA/capicxx-dbus-tools#12]
On the page https://github.com/COVESA/capicxx-dbus-tools/wiki/CommonAPI-C---D-Bus-in-10-minutes, it is mentioned "download the built code generator as binary from github". What is the link to the built code generator? 
If you mean "https://github.com/COVESA/capicxx-core-tools/releases/download/3.2.0.1/commonapi_core_generator.zip", I did not find commonapi-generator and commonapi_dbus_generator inside.

**Comment by PaulaAlessio** [comment]
https://github.com/COVESA/capicxx-core-tools/releases

**Comment by dibpinto** [comment]
Links to the build code generators are correctly indicated in previous comment.
