### ISSUE TITLE
Build failure :org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'core.cli' from location file:/home/user/vsomeip1/capicxx-dbus-tools/org.genivi.commonapi.core.cli.product/target/repository/

### ISSUE THREAD

**Issue by Vijay0292** [COVESA/capicxx-dbus-tools#13]
while running :~/vsomeip1/capicxx-dbus-tools/org.genivi.commonapi.dbus.releng$ mvn -DCOREPATH=/home/v-mathaiyan/vsomeip1/capicxx-dbus-tools -Dtarget.id=org.genivi.commonapi.dbus.target clean verify
build is failing and shows the following error.

"org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'core.cli' from location file:/home/v-mathaiyan/vsomeip1/capicxx-dbus-tools/org.genivi.commonapi.core.cli.product/target/repository/"

"Failed to load p2 repository with ID 'core.cli' from location file:/home/v-mathaiyan/vsomeip1/capicxx-dbus-tools/org.genivi.commonapi.core.cli.product/target/repository/"

"Caused by: org.eclipse.equinox.p2.core.ProvisionException: No repository found at file:/home/v-mathaiyan/vsomeip1/capicxx-dbus-tools/org.genivi.commonapi.core.cli.product/target/repository."

**Comment by goncaloalmeida** [comment]
@Vijay0292 this problem is still reproducible?
