### ISSUE TITLE
Build failed for the 3.2.14

### ISSUE THREAD

**Issue by lijie-jiang** [COVESA/capicxx-dbus-tools#15]
Issue the command below but the build complain and output errors, while the core-tool and someip-tool work.

`mvn -DCOREPATH=/home/github/capicxx-core-tools -Dtarget.id=org.genivi.commonapi.dbus.target clean verify`

> 
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] org.genivi.commonapi.dbus.target ................... SUCCESS [  1.494 s]
[INFO] org.genivi.commonapi.dbus.releng ................... SUCCESS [  0.002 s]
[INFO] org.genivi.commonapi.dbus .......................... FAILURE [  4.580 s]
[INFO] org.genivi.commonapi.dbus.cli ...................... SKIPPED
[INFO] org.genivi.commonapi.dbus.cli.feature .............. SKIPPED
[INFO] org.genivi.commonapi.dbus.cli.product .............. SKIPPED
[INFO] org.genivi.commonapi.dbus.ui ....................... SKIPPED
[INFO] org.genivi.commonapi.dbus.feature .................. SKIPPED
[INFO] org.genivi.commonapi.dbus.validator ................ SKIPPED
[INFO] org.genivi.commonapi.dbus.validator.feature ........ SKIPPED
[INFO] org.genivi.commonapi.dbus.updatesite ............... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18:42 min
[INFO] Finished at: 2023-11-02T17:41:38+08:00
[INFO] Final Memory: 143M/816M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.22.0:compile (default-compile) on project org.genivi.commonapi.dbus: Compilation failure: Compilation failure: 
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[21] 
[ERROR] 	import org.genivi.commonapi.dbus.Deployment;
[ERROR] 	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.genivi.commonapi.dbus.Deployment cannot be resolved
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[25] 
[ERROR] 	Deployment.IDataPropertyAccessor dbusDataAccessor_;
[ERROR] 	^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[26] 
[ERROR] 	Deployment.ProviderPropertyAccessor dbusProvider_;
[ERROR] 	^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[40] 
[ERROR] 	dbusDataAccessor_ = null;
[ERROR] 	^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[41] 
[ERROR] 	dbusProvider_ = null;
[ERROR] 	^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[48] 
[ERROR] 	dbusDataAccessor_ = new Deployment.InterfacePropertyAccessor(_target);
[ERROR] 	^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[48] 
[ERROR] 	dbusDataAccessor_ = new Deployment.InterfacePropertyAccessor(_target);
[ERROR] 	                        ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[49] 
[ERROR] 	dbusProvider_ = null;
[ERROR] 	^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[56] 
[ERROR] 	dbusDataAccessor_ = new Deployment.TypeCollectionPropertyAccessor(_target);
[ERROR] 	^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[56] 
[ERROR] 	dbusDataAccessor_ = new Deployment.TypeCollectionPropertyAccessor(_target);
[ERROR] 	                        ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[57] 
[ERROR] 	dbusProvider_ = null;
[ERROR] 	^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[64] 
[ERROR] 	dbusProvider_ = new Deployment.ProviderPropertyAccessor(_target);
[ERROR] 	^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[64] 
[ERROR] 	dbusProvider_ = new Deployment.ProviderPropertyAccessor(_target);
[ERROR] 	                    ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[66] 
[ERROR] 	dbusDataAccessor_ = null;
[ERROR] 	^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[71] 
[ERROR] 	dbusProvider_ = null;
[ERROR] 	^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[72] 
[ERROR] 	if (_parent.type_ != DeploymentType.PROVIDER && _parent != null && _parent.dbusDataAccessor_ != null) {
[ERROR] 	                                                                           ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved or is not a field
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[73] 
[ERROR] 	dbusDataAccessor_ = _parent.dbusDataAccessor_.getOverwriteAccessor(_element);
[ERROR] 	^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[73] 
[ERROR] 	dbusDataAccessor_ = _parent.dbusDataAccessor_.getOverwriteAccessor(_element);
[ERROR] 	                            ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved or is not a field
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[77] 
[ERROR] 	dbusDataAccessor_ = null;
[ERROR] 	^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[83] 
[ERROR] 	dbusProvider_ = null;
[ERROR] 	^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[84] 
[ERROR] 	if (_parent.type_ != DeploymentType.PROVIDER && _parent != null && _parent.dbusDataAccessor_ != null) {
[ERROR] 	                                                                           ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved or is not a field
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[85] 
[ERROR] 	dbusDataAccessor_ = _parent.dbusDataAccessor_.getOverwriteAccessor(_element);
[ERROR] 	^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[85] 
[ERROR] 	dbusDataAccessor_ = _parent.dbusDataAccessor_.getOverwriteAccessor(_element);
[ERROR] 	                            ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved or is not a field
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[89] 
[ERROR] 	dbusDataAccessor_ = null;
[ERROR] 	^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[95] 
[ERROR] 	dbusProvider_ = null;
[ERROR] 	^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[97] 
[ERROR] 	Deployment.InterfacePropertyAccessor ipa = (Deployment.InterfacePropertyAccessor) _parent.dbusDataAccessor_;
[ERROR] 	^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[97] 
[ERROR] 	Deployment.InterfacePropertyAccessor ipa = (Deployment.InterfacePropertyAccessor) _parent.dbusDataAccessor_;
[ERROR] 	                                            ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[97] 
[ERROR] 	Deployment.InterfacePropertyAccessor ipa = (Deployment.InterfacePropertyAccessor) _parent.dbusDataAccessor_;
[ERROR] 	                                                                                          ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved or is not a field
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[98] 
[ERROR] 	dbusDataAccessor_ = ipa.getOverwriteAccessor(_element);
[ERROR] 	^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[101] 
[ERROR] 	dbusDataAccessor_ = null;
[ERROR] 	^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[107] 
[ERROR] 	dbusProvider_ = null;
[ERROR] 	^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[109] 
[ERROR] 	Deployment.InterfacePropertyAccessor ipa = (Deployment.InterfacePropertyAccessor) _parent.dbusDataAccessor_;
[ERROR] 	^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[109] 
[ERROR] 	Deployment.InterfacePropertyAccessor ipa = (Deployment.InterfacePropertyAccessor) _parent.dbusDataAccessor_;
[ERROR] 	                                            ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[109] 
[ERROR] 	Deployment.InterfacePropertyAccessor ipa = (Deployment.InterfacePropertyAccessor) _parent.dbusDataAccessor_;
[ERROR] 	                                                                                          ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved or is not a field
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[110] 
[ERROR] 	dbusDataAccessor_ = ipa.getOverwriteAccessor(_element);
[ERROR] 	^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[113] 
[ERROR] 	dbusDataAccessor_ = null;
[ERROR] 	^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[144] 
[ERROR] 	if (dbusDataAccessor_ != parent_.dbusDataAccessor_) {
[ERROR] 	    ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[144] 
[ERROR] 	if (dbusDataAccessor_ != parent_.dbusDataAccessor_) {
[ERROR] 	                                 ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved or is not a field
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[178] 
[ERROR] 	return (type_ == DeploymentType.OVERWRITE && !hasSameAccessor(dbusDataAccessor_));
[ERROR] 	                                                              ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[180] 
[ERROR] 	protected boolean hasSameAccessor(Deployment.IDataPropertyAccessor _accessor)
[ERROR] 	                                  ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[184] 
[ERROR] 	if (parent_.dbusDataAccessor_ == _accessor)
[ERROR] 	            ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved or is not a field
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[191] 
[ERROR] 	return from(((Deployment.InterfacePropertyAccessor)dbusDataAccessor_).getDBusDefaultAttributeType(obj));
[ERROR] 	              ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[191] 
[ERROR] 	return from(((Deployment.InterfacePropertyAccessor)dbusDataAccessor_).getDBusDefaultAttributeType(obj));
[ERROR] 	                                                   ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[199] 
[ERROR] 	private PropertiesType from(Deployment.Enums.DBusDefaultAttributeType _source) {
[ERROR] 	                            ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[202] 
[ERROR] 	case freedesktop:
[ERROR] 	     ^^^^^^^^^^^
[ERROR] freedesktop cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[216] 
[ERROR] 	return dbusDataAccessor_.getIsObjectPath(obj);
[ERROR] 	       ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[226] 
[ERROR] 	return dbusDataAccessor_.getIsUnixFD(obj);
[ERROR] 	       ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[234] 
[ERROR] 	return from(dbusDataAccessor_.getDBusVariantType(obj));
[ERROR] 	            ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[240] 
[ERROR] 	private DBusVariantType from(Deployment.Enums.DBusVariantType type)
[ERROR] 	                             ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[244] 
[ERROR] 	case CommonAPI:
[ERROR] 	     ^^^^^^^^^
[ERROR] CommonAPI cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[246] 
[ERROR] 	case DBus:
[ERROR] 	     ^^^^
[ERROR] DBus cannot be resolved to a variable
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[256] 
[ERROR] 	return dbusProvider_.getDBusInterfaceName(obj);
[ERROR] 	       ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[265] 
[ERROR] 	return dbusProvider_.getDBusObjectPath(obj);
[ERROR] 	       ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[274] 
[ERROR] 	return dbusProvider_.getDBusServiceName(obj);
[ERROR] 	       ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[283] 
[ERROR] 	return dbusProvider_.getDomain(obj);
[ERROR] 	       ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[292] 
[ERROR] 	return dbusProvider_.getInstanceId(obj);
[ERROR] 	       ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved
[ERROR] /home/lijiejiang/github/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[302] 
[ERROR] 	isDBusPredefined = dbusProvider_.getDBusPredefined(obj);
[ERROR] 	                   ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved
[ERROR] 57 problems (57 errors)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.genivi.commonapi.dbus

>

**Comment by goncaloalmeida** [comment]
hello @lijie-jiang the problem is now solved! thanks for the input :)

cc @DiogoPedrozza @dibpinto @Gustavo1515
