### ISSUE TITLE
how to change default  DBusInterfaceName to a user choice DBusInterfaceName 

### ISSUE THREAD

**Issue by rocksankalp** [COVESA/capicxx-dbus-tools#8]
Hi All,

i want my own choice DBusInterfaceName ;
CommonAPI-Dbus generatore alway adds suffix version no(minor,major ) to DBusInterfaceName .

i am trying to get my own choice of DBusInterfaceName .

i tried few of the suggestion found over internet provided by GENIVI forums over here .
https://github.com/GENIVI/capicxx-dbus-tools/blob/master/org.genivi.commonapi.dbus/deployment/CommonAPI-DBus_deployment_spec.fdepl
it didn't worked for me .
can you let me know if with latest CommonAPI D-bus version why above link solution is not  working .

i have also tried to change interface name through Common-api-dbus.ini files 
like mentioned here 
https://github.com/GENIVI/navigation-application/blob/master/src/commonapi-dbus.ini
changing interface name from .ini as mentioned in the above link also didn't hel me .

i am attaching my .fdepl ->extension changed to .txt 
 file and .ini file(extension changed) to .ini) over here pls check and let me know if any correction there.
[commonapi-dbus.txt](https://github.com/GENIVI/capicxx-dbus-tools/files/5311350/commonapi-dbus.txt)
[EchoFrancaService.txt](https://github.com/GENIVI/capicxx-dbus-tools/files/5311351/EchoFrancaService.txt)

or there anything i am missing so far ?

thanks

**Comment by goncaloalmeida** [comment]
@rocksankalp you still have this question?
