### ISSUE TITLE
capicxx-dbus-tools build failed with "import org.genivi.commonapi.dbus.Deployment;"

### ISSUE THREAD

**Issue by rayen1119** [COVESA/capicxx-dbus-tools#9]
Hello All, 
I try build the capicxx-dbus-tools by myself, but failed. detailed info listed below.
What's wrong happened?
Thank you.

## ubuntu 20.04 on VirtualBox
(base) XyXy@osboxes:~/workshop$ uname -a
Linux osboxes 5.11.0-22-generic #23-Ubuntu SMP Thu Jun 17 00:34:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

## Java version
(base) XyXy@osboxes:~/workshop$ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment Corretto-8.292.10.1 (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM Corretto-8.292.10.1 (build 25.292-b10, mixed mode)

## maven version
(base) XyXy@osboxes:~/workshop/capicxx-dbus-tools$ mvn -version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 1.8.0_292, vendor: Amazon.com Inc., runtime: /usr/lib/jvm/java-1.8.0-amazon-corretto/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.11.0-22-generic", arch: "amd64", family: "unix"

## the newest codes
https://github.com/GENIVI/capicxx-dbus-tools.git

## start build process of capicxx-dbus-tools
(base) XyXy@osboxes:~/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus.releng$ mvn -DCOREPATH=/home/XyXy/workshop/capicxx-core-tools -Dtarget.id=org.genivi.commonapi.dbus.target clean verify
[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: commonapi:org.genivi.commonapi.dbus:3.2.0-SNAPSHOT @ /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/pom.xml
[INFO] Fetching p2.index from http://download.eclipse.org/eclipse/updates/4.9/ (0B of 128B at 0B/s)
[INFO] Adding repository http://download.eclipse.org/eclipse/updates/4.9
[INFO] Fetching p2.index from http://download.eclipse.org/eclipse/updates/4.9/R-4.9-201809060745/ (0B of 142B at 0B/s)
[INFO] Fetching p2.index from http://download.eclipse.org/releases/2018-09/ (0B of 122B at 0B/s)
[INFO] Adding repository http://download.eclipse.org/releases/2018-09
...
...
 --- maven-resources-plugin:2.4.3:resources (default-resources) @ org.genivi.commonapi.dbus ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/main/resources
[INFO]
[INFO] --- tycho-compiler-plugin:0.22.0:compile (default-compile) @ org.genivi.commonapi.dbus ---
[INFO] Compiling 14 source files to /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for org.genivi.commonapi.dbus.releng 3.2.0-SNAPSHOT:
[INFO]
[INFO] org.genivi.commonapi.dbus.target ................... SUCCESS [  3.188 s]
[INFO] org.genivi.commonapi.dbus.releng ................... SUCCESS [  0.023 s]
[INFO] org.genivi.commonapi.dbus .......................... FAILURE [  8.597 s]
[INFO] org.genivi.commonapi.dbus.cli ...................... SKIPPED
[INFO] org.genivi.commonapi.dbus.cli.feature .............. SKIPPED
[INFO] org.genivi.commonapi.dbus.cli.product .............. SKIPPED
[INFO] org.genivi.commonapi.dbus.ui ....................... SKIPPED
[INFO] org.genivi.commonapi.dbus.feature .................. SKIPPED
[INFO] org.genivi.commonapi.dbus.validator ................ SKIPPED
[INFO] org.genivi.commonapi.dbus.validator.feature ........ SKIPPED
[INFO] org.genivi.commonapi.dbus.updatesite ............... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:54 min
[INFO] Finished at: 2021-07-01T02:37:25-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.22.0:compile (default-compile) on project org.genivi.commonapi.dbus: Compilation failure: Compilation failure:
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[21]
[ERROR]         import org.genivi.commonapi.dbus.Deployment;
[ERROR]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.genivi.commonapi.dbus.Deployment cannot be resolved
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[25]
[ERROR]         Deployment.IDataPropertyAccessor dbusDataAccessor_;
[ERROR]         ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[26]
[ERROR]         Deployment.ProviderPropertyAccessor dbusProvider_;
[ERROR]         ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[40]
[ERROR]         dbusDataAccessor_ = null;
[ERROR]         ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[41]
[ERROR]         dbusProvider_ = null;
[ERROR]         ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[48]
[ERROR]         dbusDataAccessor_ = new Deployment.InterfacePropertyAccessor(_target);
[ERROR]         ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[48]
[ERROR]         dbusDataAccessor_ = new Deployment.InterfacePropertyAccessor(_target);
[ERROR]                                 ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[49]
[ERROR]         dbusProvider_ = null;
[ERROR]         ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[56]
[ERROR]         dbusDataAccessor_ = new Deployment.TypeCollectionPropertyAccessor(_target);
[ERROR]         ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[56]
[ERROR]         dbusDataAccessor_ = new Deployment.TypeCollectionPropertyAccessor(_target);
[ERROR]                                 ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[57]
[ERROR]         dbusProvider_ = null;
[ERROR]         ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[64]
[ERROR]         dbusProvider_ = new Deployment.ProviderPropertyAccessor(_target);
[ERROR]         ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[64]
[ERROR]         dbusProvider_ = new Deployment.ProviderPropertyAccessor(_target);
[ERROR]                             ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[66]
[ERROR]         dbusDataAccessor_ = null;
[ERROR]         ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[71]
[ERROR]         dbusProvider_ = null;
[ERROR]         ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[72]
[ERROR]         if (_parent.type_ != DeploymentType.PROVIDER && _parent != null && _parent.dbusDataAccessor_ != null) {
[ERROR]                                                                                    ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved or is not a field
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[73]
[ERROR]         dbusDataAccessor_ = _parent.dbusDataAccessor_.getOverwriteAccessor(_element);
[ERROR]         ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[73]
[ERROR]         dbusDataAccessor_ = _parent.dbusDataAccessor_.getOverwriteAccessor(_element);
[ERROR]                                     ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved or is not a field
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[77]
[ERROR]         dbusDataAccessor_ = null;
[ERROR]         ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[83]
[ERROR]         dbusProvider_ = null;
[ERROR]         ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[84]
[ERROR]         if (_parent.type_ != DeploymentType.PROVIDER && _parent != null && _parent.dbusDataAccessor_ != null) {
[ERROR]                                                                                    ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved or is not a field
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[85]
[ERROR]         dbusDataAccessor_ = _parent.dbusDataAccessor_.getOverwriteAccessor(_element);
[ERROR]         ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[85]
[ERROR]         dbusDataAccessor_ = _parent.dbusDataAccessor_.getOverwriteAccessor(_element);
[ERROR]                                     ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved or is not a field
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[89]
[ERROR]         dbusDataAccessor_ = null;
[ERROR]         ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[95]
[ERROR]         dbusProvider_ = null;
[ERROR]         ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[97]
[ERROR]         Deployment.InterfacePropertyAccessor ipa = (Deployment.InterfacePropertyAccessor) _parent.dbusDataAccessor_;
[ERROR]         ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[97]
[ERROR]         Deployment.InterfacePropertyAccessor ipa = (Deployment.InterfacePropertyAccessor) _parent.dbusDataAccessor_;
[ERROR]                                                     ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[97]
[ERROR]         Deployment.InterfacePropertyAccessor ipa = (Deployment.InterfacePropertyAccessor) _parent.dbusDataAccessor_;
[ERROR]                                                                                                   ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved or is not a field
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[98]
[ERROR]         dbusDataAccessor_ = ipa.getOverwriteAccessor(_element);
[ERROR]         ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[101]
[ERROR]         dbusDataAccessor_ = null;
[ERROR]         ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[107]
[ERROR]         dbusProvider_ = null;
[ERROR]         ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[109]
[ERROR]         Deployment.InterfacePropertyAccessor ipa = (Deployment.InterfacePropertyAccessor) _parent.dbusDataAccessor_;
[ERROR]         ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[109]
[ERROR]         Deployment.InterfacePropertyAccessor ipa = (Deployment.InterfacePropertyAccessor) _parent.dbusDataAccessor_;
[ERROR]                                                     ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[109]
[ERROR]         Deployment.InterfacePropertyAccessor ipa = (Deployment.InterfacePropertyAccessor) _parent.dbusDataAccessor_;
[ERROR]                                                                                                   ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved or is not a field
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[110]
[ERROR]         dbusDataAccessor_ = ipa.getOverwriteAccessor(_element);
[ERROR]         ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[113]
[ERROR]         dbusDataAccessor_ = null;
[ERROR]         ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[144]
[ERROR]         if (dbusDataAccessor_ != parent_.dbusDataAccessor_) {
[ERROR]             ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[144]
[ERROR]         if (dbusDataAccessor_ != parent_.dbusDataAccessor_) {
[ERROR]                                          ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved or is not a field
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[178]
[ERROR]         return (type_ == DeploymentType.OVERWRITE && !hasSameAccessor(dbusDataAccessor_));
[ERROR]                                                                       ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[180]
[ERROR]         protected boolean hasSameAccessor(Deployment.IDataPropertyAccessor _accessor)
[ERROR]                                           ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[184]
[ERROR]         if (parent_.dbusDataAccessor_ == _accessor)
[ERROR]                     ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved or is not a field
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[191]
[ERROR]         return from(((Deployment.InterfacePropertyAccessor)dbusDataAccessor_).getDBusDefaultAttributeType(obj));
[ERROR]                       ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[191]
[ERROR]         return from(((Deployment.InterfacePropertyAccessor)dbusDataAccessor_).getDBusDefaultAttributeType(obj));
[ERROR]                                                            ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[199]
[ERROR]         private PropertiesType from(Deployment.Enums.DBusDefaultAttributeType _source) {
[ERROR]                                     ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[202]
[ERROR]         case freedesktop:
[ERROR]              ^^^^^^^^^^^
[ERROR] freedesktop cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[216]
[ERROR]         isObjectPath = dbusDataAccessor_.getIsObjectPath(obj);
[ERROR]                        ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[226]
[ERROR]         isUnixFD = dbusDataAccessor_.getIsUnixFD(obj);
[ERROR]                    ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[236]
[ERROR]         variantType = from(dbusDataAccessor_.getDBusVariantType(obj));
[ERROR]                            ^^^^^^^^^^^^^^^^^
[ERROR] dbusDataAccessor_ cannot be resolved
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[242]
[ERROR]         private DBusVariantType from(Deployment.Enums.DBusVariantType type)
[ERROR]                                      ^^^^^^^^^^
[ERROR] Deployment cannot be resolved to a type
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[246]
[ERROR]         case CommonAPI:
[ERROR]              ^^^^^^^^^
[ERROR] CommonAPI cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[248]
[ERROR]         case DBus:
[ERROR]              ^^^^
[ERROR] DBus cannot be resolved to a variable
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[258]
[ERROR]         return dbusProvider_.getDBusInterfaceName(obj);
[ERROR]                ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[267]
[ERROR]         return dbusProvider_.getDBusObjectPath(obj);
[ERROR]                ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[276]
[ERROR]         return dbusProvider_.getDBusServiceName(obj);
[ERROR]                ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[285]
[ERROR]         return dbusProvider_.getDomain(obj);
[ERROR]                ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[294]
[ERROR]         return dbusProvider_.getInstanceId(obj);
[ERROR]                ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved
[ERROR] /home/XyXy/workshop/capicxx-dbus-tools/org.genivi.commonapi.dbus/src/org/genivi/commonapi/dbus/deployment/PropertyAccessor.java:[304]
[ERROR]         isDBusPredefined = dbusProvider_.getDBusPredefined(obj);
[ERROR]                            ^^^^^^^^^^^^^
[ERROR] dbusProvider_ cannot be resolved
[ERROR] 57 problems (57 errors)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :org.genivi.commonapi.dbus

**Comment by bum2free** [comment]
Yes, there is due to lacking of some files, which are included in the core-tools and someip-tools(by the patch of 3.2.0.1 version upload), but missing for dbus-tools

**Comment by goncaloalmeida** [comment]
@rayen1119 you are still with this problem?
